name: Build Next.js static site

on: workflow_call

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  checks: write
  id-token: write

# Set working directory
defaults:
  run:
    working-directory: ./docs

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Print working directory
        run: |
          pwd
          ls

      - name: Install dependencies
        run: bun install

      - name: Print working directory
        run: |
          pwd
          ls

      - name: Build with Next.js
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: ./docs/out
