name: CICD Pipeline

on: 
  push: 
    branches: ["main"]
    paths-ignore:
      - .gitignore
  
  workflow_dispatch:

jobs:
 
  build-site:
    uses: ./.github/workflows/build-static-site.yml
    secrets: inherit
    
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: staging
    secrets: inherit
    needs: build-site
  
  approval-gate:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: "prod-approval"
    concurrency:
      cancel-in-progress: true
      group: prod-approval
    steps:
      - name: Approved
        shell: bash
        run: |
          echo "Approved for Prod"

  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: prod
    secrets: inherit
    needs: approval-gate


  
    