name: CICD Pipeline

on: 
  push: 
    branches: ["main"]
    paths-ignore:
      - .gitignore
  
  workflow_dispatch:

jobs:
 
  build-site:
    uses: ./.github/workflows/build-static-site.yml
    secrets: inherit
    
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: staging
    secrets: inherit
    needs: build-site

  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: prod
    secrets: inherit
    needs: deploy-staging


  
    