name: Deploy Next.js static site

on:
  workflow_call:
    inputs:
      environment:
        description: "Name of the environment to deploy to"
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN
permissions:
    id-token: write
    contents: read
    checks: write

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP}}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}
