name: Deploy Next.js static site

on:
  workflow_call:
    inputs:
      environment:
        description: "Name of the environment to deploy to"
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN
permissions:
    id-token: write
    contents: read
    checks: write

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP}}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

    steps:
        - name: Login to Azure
          uses: azure/login@v1
          with:
            client-id: ${{ env.CLIENT_ID }}
            tenant-id: ${{ env.TENANT_ID }}
            subscription-id: ${{ env.SUBSCRIPTION_ID }}

        # - name: Download all workflow run artifacts
        #   uses: actions/download-artifact@v3
        #   with:
        #     name: out

        - name: Print working directory
          run: ls

        # - name: List blob storage
        #   uses: azure/CLI@v1
        #   with:
        #     inlineScript: |
        #       az storage blob list --account-name sswdory --auth-mode key -c '$web'
        - run: |
            az upgrade
            az --version
            az storage blob list --account-name sswdory --container-name $web
