name: Deploy Next.js static site

on: workflow_call

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP}}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}
